name: Daily process (crash reports, update translations)
on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron: "0 23 * * *"
jobs:
  build:
    name: Build
    runs-on: windows-2022
    steps:
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Check out source code
        uses: actions/checkout@v2

      - name: update translations
        env:
          TRANS_UPLOAD_SECRET: ${{ secrets.TRANS_UPLOAD_SECRET }}
        run: .\doit.bat -ci-trans-update
